/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.tpcs_practica01;

import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class EmpleadoGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpleadoGUI
     */
    public EmpleadoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bt_Nuevo = new javax.swing.JButton();
        bt_Modificar = new javax.swing.JButton();
        bt_Eliminar = new javax.swing.JButton();
        bt_Buscar = new javax.swing.JButton();
        bt_todo = new javax.swing.JButton();
        panel_principal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Catalogo_Empleado");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jToolBar1.setRollover(true);

        bt_Nuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Documents\\NetBeansProjects\\Tecnologias de Construccion\\Practica_01\\TPCS_Practica01\\imagenes\\iconos\\guardar.png")); // NOI18N
        bt_Nuevo.setToolTipText("Guardar");
        bt_Nuevo.setFocusable(false);
        bt_Nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_NuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_Nuevo);

        bt_Modificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Documents\\NetBeansProjects\\Tecnologias de Construccion\\Practica_01\\TPCS_Practica01\\imagenes\\iconos\\modificar.png")); // NOI18N
        bt_Modificar.setToolTipText("Modificar");
        bt_Modificar.setFocusable(false);
        bt_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_Modificar);

        bt_Eliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Documents\\NetBeansProjects\\Tecnologias de Construccion\\Practica_01\\TPCS_Practica01\\imagenes\\iconos\\eliminar.png")); // NOI18N
        bt_Eliminar.setToolTipText("Eliminar");
        bt_Eliminar.setFocusable(false);
        bt_Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_Eliminar);

        bt_Buscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Documents\\NetBeansProjects\\Tecnologias de Construccion\\Practica_01\\TPCS_Practica01\\imagenes\\iconos\\buscar.png")); // NOI18N
        bt_Buscar.setToolTipText("Buscar");
        bt_Buscar.setFocusable(false);
        bt_Buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_Buscar);

        bt_todo.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Documents\\NetBeansProjects\\Tecnologias de Construccion\\Practica_01\\TPCS_Practica01\\imagenes\\iconos\\actualizar.png")); // NOI18N
        bt_todo.setToolTipText("Actualizar");
        bt_todo.setFocusable(false);
        bt_todo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_todo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_todoActionPerformed(evt);
            }
        });
        jToolBar1.add(bt_todo);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Nombre");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Direccion");

        jLabel4.setText("Telefono");

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });

        jLabel1.setText("Clave");

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_clave)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(23, 113, Short.MAX_VALUE))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(panel_principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NuevoActionPerformed
        // TODO add your handling code here:
        
        LDAOEmpleado em = new LDAOEmpleado();
        DAOEmpleado dao = new DAOEmpleado();
        
        Empleado emp = new Empleado();
        emp.setNombre(txt_nombre.getText());
        emp.setDireccion(txt_direccion.getText());
        emp.setTelefono(txt_telefono.getText());
        
        em.saveEmpleado(emp);
        
        bt_todo.doClick();
        
    }//GEN-LAST:event_bt_NuevoActionPerformed

    private void bt_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModificarActionPerformed
        // TODO add your handling code here:
        
        LDAOEmpleado em = new LDAOEmpleado();
        
        Empleado emp = new Empleado();
        emp.setNombre(txt_nombre.getText());
        emp.setDireccion(txt_direccion.getText());
        emp.setTelefono(txt_telefono.getText());
        int clave = Integer.parseInt(txt_clave.getText());
        em.updateEmpleado(emp, clave);
        
        bt_todo.doClick();
        
    }//GEN-LAST:event_bt_ModificarActionPerformed

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        // TODO add your handling code here:
        
        LDAOEmpleado em = new LDAOEmpleado();
        
        int clave = Integer.parseInt(txt_clave.getText());
        em.deleteEmpleado(clave);
        
        bt_todo.doClick();
        
    }//GEN-LAST:event_bt_EliminarActionPerformed

    private void bt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BuscarActionPerformed
        // TODO add your handling code here:
        
        LDAOEmpleado em = new LDAOEmpleado();
        
        int clave = Integer.parseInt(txt_clave.getText());
        
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Dirección");
            modelo.addColumn("Teléfono");
            
            Empleado emp = em.findEmpleadoById(clave);
            long id = emp.getClave();
            String nombre = emp.getNombre();
            String direccion = emp.getDireccion();
            String telefono = emp.getTelefono();
            
                modelo.addRow(new Object[]{id, nombre, direccion, telefono});
            jTable1.setModel(modelo);
        }catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_bt_BuscarActionPerformed

    private void bt_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_todoActionPerformed
        // TODO add your handling code here:
        
        LDAOEmpleado dao = new LDAOEmpleado();
        List<Empleado> lstEmpleado=dao.findAllEmpleados();
        
        Iterator<Empleado> it = lstEmpleado.iterator();
        
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Dirección");
            modelo.addColumn("Teléfono");
            
            while(it.hasNext()){
                Empleado emp = it.next();
                long id = emp.getClave();
                String nombre = emp.getNombre();
                String direccion = emp.getDireccion();
                String telefono = emp.getTelefono();

                modelo.addRow(new Object[]{id, nombre, direccion, telefono});
            }
            jTable1.setModel(modelo);
        }catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_bt_todoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Buscar;
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JButton bt_Modificar;
    private javax.swing.JButton bt_Nuevo;
    private javax.swing.JButton bt_todo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
